### ISSUE TITLE
Error on Macbook Pro 2.1 - OS X 10.5.7

### ISSUE THREAD

**Issue by JulianBashir** [linusbobcat/create-elementary-os-installer#63]
### Expected behaviour
Expected it to burn to the USB drive
### Actual behaviour
Keep getting an error saying could not find /dev/rdiskX
I have checked using DiskUtil and terminal the drive is there and was formatted to MAC journalled and FAT.
Name of drive "elementary OS"
Keep getting this error. Note this is not about booting, it is about being able to flash the USB

PS. Thanks for the tool.

### Steps to reproduce the behaviour
1.
2.
3.

### System Information
- elementaryos-0.4-stable-amd64.20160921.iso
- Mac OS X version 10.5.7
- Create elementary OS Installer version - 0.2.9
- Mac model (Macbook Pro 2.1 Late 2006)
- Computer language (if you're having a localization issue)

/*Note:
Go to "About This Mac" or "About This Mac" followed by "More Info" to find out your Mac model. Any Mac made around 2010-2012 or before that may have issues booting elementary OS from a USB Drive, there is nothing I can do about that.
*/

**Comment by linusbobcat** [comment]
Hi, unfortunately I haven't been able to test this app on anything below
Mac OS X 10.6. I also don't have time to maintain this anymore.

You can however use the command line to manually write the elementary OS
ISO to the USB Drive. See the second answer here:
https://apple.stackexchange.com/questions/73183/copying-iso-file-to-usb-drive-in-os-x


On Apr 24, 2017 4:10 PM, "JulianBashir" <notifications@github.com> wrote:

Expected behaviour

Expected it to burn to the USB drive
Actual behaviour

Keep getting an error saying could not find /dev/rdiskX
I have checked using DiskUtil and terminal the drive is there and was
formatted to MAC journalled and FAT.
Name of drive "elementary OS"
Keep getting this error. Note this is not about booting, it is about being
able to flash the USB

PS. Thanks for the tool.
Steps to reproduce the behaviour

   1.
   2.
   3.

System Information

   - elementaryos-0.4-stable-amd64.20160921.iso
   - Mac OS X version 10.5.7
   - Create elementary OS Installer version - 0.2.9
   - Mac model (Macbook Pro 2.1 Late 2006)
   - Computer language (if you're having a localization issue)

/*Note:
Go to "About This Mac" or "About This Mac" followed by "More Info" to find
out your Mac model. Any Mac made around 2010-2012 or before that may have
issues booting elementary OS from a USB Drive, there is nothing I can do
about that.
*/

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/linusbobcat/create-elementary-os-installer/issues/63>,
or mute the thread
